parameters:

services:
    # Product
    msi_store_product_admin:
        class: %msi_store.product.admin%
        arguments: [ @msi_store.product_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    msi_store.product_manager:
        class: %msi_cmf.manager.class%
        arguments: [ %msi_store.product.class% ]
        parent: msi_cmf.manager

    # Order
    msi_store_order_admin:
        class: %msi_store.order.admin%
        arguments: [ @msi_store.order_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    msi_store.order_manager:
        class: %msi_cmf.manager.class%
        arguments: [ %msi_store.order.class% ]
        parent: msi_cmf.manager

    # Category
    msi_store_category_admin:
        class: %msi_store.category.admin%
        arguments: [ @msi_store.category_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    msi_store.category_manager:
        class: %msi_cmf.manager.class%
        arguments: [ %msi_store.category.class% ]
        parent: msi_cmf.manager
