msi_store_order_show:
    pattern:  /cart
    defaults: { _controller: MsiStoreBundle:Order:show }

msi_store_checkout_review:
    pattern:  /review
    defaults: { _controller: MsiStoreBundle:Checkout:review }

msi_store_checkout_address:
    pattern:  /address
    defaults: { _controller: MsiStoreBundle:Checkout:address }

msi_store_checkout_payment:
    pattern:  /payment
    defaults: { _controller: MsiStoreBundle:Checkout:payment }

msi_store_checkout_confirmation:
    pattern:  /confirmation
    defaults: { _controller: MsiStoreBundle:Checkout:confirmation }

msi_store_detail_new:
    pattern:  /details/new
    defaults: { _controller: MsiStoreBundle:Detail:new }

msi_store_detail_edit:
    pattern:  /details/{id}/edit
    defaults: { _controller: MsiStoreBundle:Detail:edit }

msi_store_detail_delete:
    pattern:  /details/{id}/delete
    defaults: { _controller: MsiStoreBundle:Detail:delete }

msi_store_product_index:
    pattern:  /products
    defaults: { _controller: MsiStoreBundle:Product:index }

msi_store_product_show:
    pattern:  /products/{id}
    defaults: { _controller: MsiStoreBundle:Product:show }
