msi_store_order_show:
    pattern:  /cart
    defaults: { _controller: MsiStoreBundle:Order:show }

msi_store_order_checkout:
    pattern:  /checkout
    defaults: { _controller: MsiStoreBundle:Order:checkout }

msi_store_detail_new:
    pattern:  /detail/new
    defaults: { _controller: MsiStoreBundle:Detail:new }

msi_store_detail_edit:
    pattern:  /detail/{id}/edit
    defaults: { _controller: MsiStoreBundle:Detail:edit }

msi_store_detail_delete:
    pattern:  /detail/{id}/delete
    defaults: { _controller: MsiStoreBundle:Detail:delete }

msi_store_product_index:
    pattern:  /product/list
    defaults: { _controller: MsiStoreBundle:Product:index }

msi_store_product_show:
    pattern:  /product/{id}
    defaults: { _controller: MsiStoreBundle:Product:show }
