parameters:
#    msi_store.example.class: Msi\StoreBundle\Example

services:
#    msi_store.example:
#        class: %msi_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
