parameters:
#    msi_store.example.class: Msi\StoreBundle\Example

services:
    msi_store.provider:
        class: Msi\StoreBundle\Provider\Provider
        arguments: [ @service_container ]
        scope: request

    msi_store.login_listener:
        class: Msi\StoreBundle\EventListener\LoginListener
        arguments: [ @msi_store.order_manager ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }

    msi_store.cookie_listener:
        class: Msi\StoreBundle\EventListener\CookieListener
        arguments: [ @msi_store.provider ]
        scope: request
