parameters:
#    msi_store.example.class: Msi\StoreBundle\Example

services:
    msi_store.provider:
        class: Msi\StoreBundle\Provider\Provider
        arguments: [ @service_container ]
        scope: request
